export const FIND_ACTIONS = {
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  TOGGLE_ADD_USER_MODAL_TO: "TOGGLE_ADD_USER_MODAL_TO",
  TOGGLE_SETTING_MODAL_TO: "TOGGLE_SETTING_MODAL_TO",
};
